from src.sql import SqlTemplate

attach_ticket_query = SqlTemplate("src/sql/trips/attach_ticket.sql")
change_visibility_query = SqlTemplate("src/sql/trips/change_visibility.sql")
delete_trip_query = SqlTemplate("src/sql/trips/delete_trip.sql")
duplicate_trip_query = SqlTemplate("src/sql/trips/duplicate_trip.sql")
get_current_trip_query = SqlTemplate("src/sql/trips/get_current_trip.sql")
get_trip_query = SqlTemplate("src/sql/trips/get_trip.sql")
get_user_trips_query = SqlTemplate("src/sql/trips/get_user_trips.sql")
get_dynamic_user_trips_query = SqlTemplate("src/sql/trips/get_dynamic_user_trips.sql")
get_operators_query = SqlTemplate("src/sql/trips/get_operators.sql")
get_material_types_query = SqlTemplate("src/sql/trips/get_material_types.sql")
get_number_stations_query = SqlTemplate("src/sql/trips/get_number_stations.sql")
get_trips_country_query = SqlTemplate("src/sql/trips/get_trips_country.sql")
get_unique_user_trips_query = SqlTemplate("src/sql/trips/get_unique_user_trips.sql")
get_user_lines_query = SqlTemplate("src/sql/trips/get_user_lines.sql")
get_duplicate_query = SqlTemplate("src/sql/trips/get_duplicate.sql")
delete_user_trips_query = SqlTemplate("src/sql/trips/delete_user_trips.sql")
insert_trip_query = SqlTemplate("src/sql/trips/insert_trip.sql")
update_ticket_null_query = SqlTemplate("src/sql/trips/update_ticket_null.sql")
update_trip_query = SqlTemplate("src/sql/trips/update_trip.sql")
update_trip_type_query = SqlTemplate("src/sql/trips/update_trip_type.sql")
