# Load SQL queries as variables

initPath = open("sql/initPath.sql", "r").read()
saveQuery = open("sql/save.sql", "r").read()
getTrip = open("sql/getTrip.sql", "r").read()
getTripsCountry = open("sql/getTripsCountry.sql", "r").read()
updateTripQuery = open("sql/updateTrip.sql", "r").read()
updatePath = open("sql/updatePath.sql", "r").read()
deletePathQuery = open("sql/deletePath.sql", "r").read()
getUserLines = open("sql/getUserLines.sql", "r").read()
getUserTrips = open("sql/getUserTrips.sql", "r").read()
getUniqueUserTrips = open("sql/getUniqueUserTrips.sql", "r").read()
getOperators = open("sql/getOperators.sql", "r").read()
getMaterialTypes = open("sql/getMaterialTypes.sql", "r").read()
statsOperatorTrips = (
    open("sql/stats/CTEs/tripsCTE.sql", "r").read()
    + open("sql/stats/operators.sql", "r").read()
)
statsCountries = (
    open("sql/stats/CTEs/tripsCTE.sql", "r").read()
    + open("sql/stats/countries.sql", "r").read()
)
statsYearTrips = (
    open("sql/stats/CTEs/tripsCTE.sql", "r").read()
    + open("sql/stats/year.sql", "r").read()
)
statsRoutesTrips = (
    open("sql/stats/CTEs/tripsCTE.sql", "r").read()
    + open("sql/stats/routes.sql", "r").read()
)
statsStationsTrips = (
    open("sql/stats/CTEs/tripsCTE.sql", "r").read()
    + open("sql/stats/stations.sql", "r").read()
)
statsMaterialKm = (
    open("sql/stats/CTEs/kmCTE.sql", "r").read()
    + open("sql/stats/materialType.sql", "r").read()
)
statsMaterialTrips = (
    open("sql/stats/CTEs/tripsCTE.sql", "r").read()
    + open("sql/stats/materialType.sql", "r").read()
)
statsOperatorKm = (
    open("sql/stats/CTEs/kmCTE.sql", "r").read()
    + open("sql/stats/operators.sql", "r").read()
)
statsYearKm = (
    open("sql/stats/CTEs/kmCTE.sql", "r").read()
    + open("sql/stats/year.sql", "r").read()
)
statsRoutesKm = (
    open("sql/stats/CTEs/kmCTE.sql", "r").read()
    + open("sql/stats/routes.sql", "r").read()
)
statsStationsKm = (
    open("sql/stats/CTEs/kmCTE.sql", "r").read()
    + open("sql/stats/stations.sql", "r").read()
)
adminStats = open("sql/stats/adminStats.sql", "r").read()
leaderboardStats = open("sql/stats/leaderboardStats.sql", "r").read()
typeAvailable = open("sql/stats/typeAvailable.sql", "r").read()
getManualStationsQuery = open("sql/getManualStations.sql", "r").read()
getAirports = open("sql/getAirports.sql", "r").read()
getTrainStations = open("sql/getTrainStations.sql", "r").read()
getDuplicate = open("sql/getDuplicate.sql", "r").read()
deleteUserPath = open("sql/deleteUserPath.sql", "r").read()
deleteUserTrips = open("sql/deleteUserTrips.sql", "r").read()
publicStats = open("sql/stats/publicStats.sql", "r").read()
getLeaderboardCountries = open("sql/stats/getLeaderboardCountries.sql", "r").read()
upsertPercent = open("sql/upsertPercent.sql", "r").read()
distinctStatYears = open("sql/stats/distinctStatYears.sql", "r").read()
getTickets = open("sql/getTickets.sql", "r").read()
getTags = open("sql/getTags.sql", "r").read()
getTicket = open("sql/getTicket.sql", "r").read()
getDynamicUserTrips = open("sql/getDynamicUserTrips.sql", "r").read()
getNumberStations = open("sql/getNumberStations.sql", "r").read()
countriesLeaderboard = open("sql/stats/countriesLeaderboard.sql", "r").read()
