-- Full edit of a plan-trip from the rich editor (edit_copy): timing, all metadata,
-- and the route geometry. :geom_ewkt comes from coords_to_ewkt (NULL -> NULL geom).
UPDATE plan_trips
SET timing_mode = :timing_mode,
    start_day = :start_day,
    end_day = :end_day,
    start_time = :start_time,
    end_time = :end_time,
    start_datetime = :start_datetime,
    end_datetime = :end_datetime,
    utc_start_datetime = :utc_start_datetime,
    utc_end_datetime = :utc_end_datetime,
    estimated_trip_duration = :estimated_trip_duration,
    manual_trip_duration = :manual_trip_duration,
    origin_station = :origin_station,
    destination_station = :destination_station,
    operator = :operator,
    line_name = :line_name,
    material_type = :material_type,
    material_type_advanced = :material_type_advanced,
    reg = :reg,
    seat = :seat,
    notes = :notes,
    trip_length = :trip_length,
    countries = :countries,
    price = :price,
    currency = :currency,
    purchase_date = :purchase_date,
    booked = :booked,
    waypoints = :waypoints,
    visibility = :visibility,
    carbon = :carbon,
    power_type = :power_type,
    co2_override = :co2_override,
    geom = ST_GeomFromEWKT(:geom_ewkt),
    last_modified = :last_modified
WHERE uid = :uid AND user_id = :user_id
