"""
Cutting a multi-car wagon strip into individual vehicles.

A single drawing often holds a whole EMU or push-pull set. Both importers — the
VagonWeb one (`src/api/vagonweb.py`) and the plain admin upload
(`src/api/admin/wagons.py`) — let the admin split such a strip into one wagon per
car, so the geometry lives here and is shared by both.
"""

from collections import Counter
from pathlib import Path

from PIL import Image, ImageChops


def suggest_cuts(path: Path) -> list[int]:
    """
    Suggest x positions where a multi-car strip can be cut into individual cars.

    A car body is drawn as long horizontal bands of flat colour (roof, waist,
    skirt) that run the length of the vehicle. At a joint *every* band breaks at
    once over a few pixels. So: take the rows that are dominated by a single
    opaque colour, score each column by how many of those rows it still matches,
    and keep narrow interior runs where the score drops to zero.

    Doors break some bands too, but the roof and skirt run straight through them,
    so they never reach zero — that is what separates a door from a joint. The
    result is only a suggestion; the UI lets the admin add, move and delete cuts.
    """
    with Image.open(path) as src:
        im = src.convert("RGBA")
    w, h = im.size
    px = im.load()

    row_modal = {}
    for y in range(h):
        colour, n = Counter(px[x, y] for x in range(w)).most_common(1)[0]
        if colour[3] > 10 and n > w * 0.5:
            row_modal[y] = colour
    if len(row_modal) < 4 or w < 120:
        return []

    rows = sorted(row_modal)
    score = [sum(1 for y in rows if px[x, y] == row_modal[y]) for x in range(w)]

    # Group the columns that break every band into runs
    runs: list[list[int]] = []
    for x in range(w):
        if score[x] != 0:
            continue
        if runs and x - runs[-1][-1] <= 6:
            runs[-1].append(x)
        else:
            runs.append([x])

    margin = max(20, int(w * 0.08))  # cab noses break every band too — ignore the ends
    centres = []
    for run in runs:
        width = run[-1] - run[0] + 1
        if not 2 <= width <= 12:
            continue
        centre = (run[0] + run[-1]) // 2
        if centre < margin or centre > w - margin:
            continue
        centres.append(centre)

    # Enforce a plausible minimum car length
    kept: list[int] = []
    for c in centres:
        if c - (kept[-1] if kept else 0) >= 40:
            kept.append(c)
    return [c for c in kept if w - c >= 40]


def segments(cuts: list[int], width: int) -> list[tuple[int, int]]:
    """Turn cut positions into (x0, x1) spans covering the whole strip."""
    bounds = [0, *sorted(set(cuts)), width]
    return [(bounds[i], bounds[i + 1]) for i in range(len(bounds) - 1)]


def distinct_sides(left: Path, right: Path) -> bool:
    """
    True if `right` is a real second drawing rather than a duplicate of `left`.

    A "second side" that is byte-for-byte the same picture is really one drawing,
    and the R view has to be generated by flipping rather than stored twice.
    """
    if not right.is_file():
        return False
    with Image.open(left) as a, Image.open(right) as b:
        if a.size != b.size:
            return True
        return ImageChops.difference(a.convert("RGBA"), b.convert("RGBA")).getbbox() is not None


def crop_side(src: Path, dest: Path, x0: int, x1: int, *, mirror_box: bool = False) -> None:
    """
    Write the [x0, x1) slice of `src` to `dest`.

    `mirror_box` takes the slice from the mirrored x-range, for reading car *i* out
    of the R strip: it depicts the same set from the other side, so the car that is
    leftmost in the L view is rightmost there.
    """
    with Image.open(src) as im:
        w, h = im.size
        box = (w - x1, 0, w - x0, h) if mirror_box else (x0, 0, x1, h)
        dest.parent.mkdir(parents=True, exist_ok=True)
        if box == (0, 0, w, h):
            # Whole strip, unaltered: copy the original bytes rather than
            # round-tripping it through a re-quantisation.
            dest.write_bytes(src.read_bytes())
            return
        cut = im.convert("RGBA").crop(box)
    if dest.suffix.lower() == ".gif":
        # Quantise back to a palette with a dedicated transparent index
        quantised = cut.convert("RGB").quantize(colors=255, method=Image.MEDIANCUT)
        quantised.paste(255, cut.getchannel("A").point(lambda a: 255 if a <= 10 else 0))
        quantised.save(dest, transparency=255, optimize=True)
    else:
        cut.save(dest)


def strip_width(path: Path) -> int:
    """Pixel width of an image."""
    with Image.open(path) as im:
        return im.size[0]
